config/routes.rb
Rails.application.routes.draw do
  resources :replies
  resources :comments
  resources :contributions
  resources :users
  
  get 'comment/new'
  
  get 'static_pages/home'
  
  
  root 'static_pages#home'
  
  
  resources :static_pages do
    resources :contributions
  end
  
  resources :users do
    member do
      get :contributions, :comments, :replies, :threads
    end
  end
  
  resources :contributions do
      resources :comments
  end
  
  resources :comments do
      resources :replies
  end
  
  
  resources :contributions do
  member do
      put "like", to: "contributions#upvote"
    end
  end
  
  resources :comments do
  member do
      put "like", to: "comments#upvote"
    end
  end
  
  resources :replies do
  member do
      put "like", to: "replies#upvote"
    end
  end
  

  get 'home' => 'layouts#home'
  
  get 'login' => 'users#new'
  
  get 'contributions' => 'contributions#index'
  
  get 'asks' => 'asks#index'
  
  post '/replies' => 'replies#new'
  
  get '/auth/twitter/callback', to: 'sessions#create'
  
  delete '/sign_out', to: 'sessions#destroy'

end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :user
  belongs_to :contribution
  belongs_to :comment
  acts_as_votable
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_reply, only: [:show, :edit, :update, :destroy]

  def upvote
    
    if(current_user)
      @replies = Reply.find(params[:id])
      @replies.liked_by current_user
      @replies.update(puntos: @replies.votes_for.size)
      redirect_to "/contributions/#{@replies.contribution_id}"
    else 
      @replies = Reply.find(params[:id])
      myId = decodeToken(params[:user_token])
      @user =  User.find(myId)
      if(@user.voted_for? @replies)
         render :json => {:status => "403", :error => "El usuario ya ha votado este reply"}, status: :forbidden
      else 
        @replies.liked_by @user
        @replies.update(puntos: @replies.votes_for.size)
        
          render :json => {status => "200", :id => params[:id], :content => @replies.content, 
          :puntos => @replies.puntos ,:contribution_id => @replies.contribution_id , :user_id => @replies.user_id, :comment_id => @replies.comment_id,
          :created_at => @replies.created_at }
      end
    end
    
  end 
  
  def downvote
    @replies = Reply.find(params[:id])
    @replies.downvote_by current_user
    redirect_to :back
  end

  # GET /replies
  # GET /replies.json
  def index
    if (params[:comment_id] == nil )
      @replies = Reply.all
    else 
      @micomment = Comment.find(params[:comment_id])
      
      @replies = Reply.where(comment_id: params[:comment_id])
    end
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
    #@reply = Reply.find(params[:id])
  end

  # GET /replies/new
  def new
    @reply = Reply.new
  end

  # GET /replies/1/edit
  def edit
  end

  # POST /replies
  # POST /replies.json
  def create
    if(current_user)
      @reply = Reply.new(reply_params)
  
      respond_to do |format|
        if @reply.save
          format.html { redirect_to "/contributions/#{@reply.contribution_id}"}
          format.json { render :show, status: :created, location: @reply }
        else
          format.html { render :new }
          format.json { render json: @reply.errors, status: :unprocessable_entity }
        end
      end
    else
      miId = decodeToken(params[:user_token])
      @miuser = User.find(miId)
      @micontribution = Comment.find(params[:comment_id])
      
      params[:reply][:user_id] = miId
      params[:reply][:puntos] = 0
      @reply = Reply.new(reply_params)
      respond_to do |format|
        if @reply.save
          format.html { redirect_to "/contributions/#{@reply.contribution_id}"}
          format.json { render :show, status: :created, location: @reply }
        else
          format.html { render :new }
          format.json { render json: @reply.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /replies/1
  # PATCH/PUT /replies/1.json
  def update
    respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to @reply, notice: 'Reply was successfully updated.' }
        format.json { render :show, status: :ok, location: @reply }
      else
        format.html { render :edit }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply.destroy
    respond_to do |format|
      format.html { redirect_to replies_url, notice: 'Reply was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reply
      @reply = Reply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reply_params
      params.require(:reply).permit(:content, :puntos, :user_id, :contribution_id, :comment_id)
    end
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/replies/_form.html.erb
<%= form_for(Reply.new) do |f| %>
  <% if Reply.new.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(Reply.new.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% Reply.new.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  
  <div class="field">
    <%= f.hidden_field(:comment_id, :value => @comment.id) %>
  </div>
  
  <div class="field">
    <%= f.hidden_field(:contribution_id, :value => @comment.contribution_id) %>
  </div>
  
  <div class="field">
    <%= f.hidden_field(:user_id, :value => current_user.id) %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/replies/edit.html.erb
<h1>Editing Reply</h1>

<%= render 'form' %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', replies_path %>

app/views/replies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Replies</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
        <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New Reply</h1>

<%= render 'form' %>

<%= link_to 'Back', replies_path %>

app/views/replies/show.html.erb
  <%= render 'static_pages/header' %>
  <%= render 'static_pages/menu' %>
  
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', replies_path %>
  
  <%= render 'static_pages/footer' %>