config/routes.rb
Rails.application.routes.draw do
  resources :replies
  resources :comments
  resources :contributions
  resources :users
  
  get 'comment/new'
  
  get 'static_pages/home'
  
  
  root 'static_pages#home'
  
  
  resources :static_pages do
    resources :contributions
  end
  
  resources :users do
    member do
      get :contributions, :comments, :replies, :threads
    end
  end
  
  resources :contributions do
      resources :comments
  end
  
  resources :comments do
      resources :replies
  end
  
  
  resources :contributions do
  member do
      put "like", to: "contributions#upvote"
    end
  end
  
  resources :comments do
  member do
      put "like", to: "comments#upvote"
    end
  end
  
  resources :replies do
  member do
      put "like", to: "replies#upvote"
    end
  end
  

  get 'home' => 'layouts#home'
  
  get 'login' => 'users#new'
  
  get 'contributions' => 'contributions#index'
  
  get 'asks' => 'asks#index'
  
  post '/replies' => 'replies#new'
  
  get '/auth/twitter/callback', to: 'sessions#create'
  
  delete '/sign_out', to: 'sessions#destroy'

end

app/models/user.rb
class User < ActiveRecord::Base
        has_many :contributions, dependent: :destroy
    acts_as_voter
   
  def self.from_omniauth(auth)
    find_by(provider: auth['provider'], uid: auth['uid']) || create_user_from_omniauth(auth)
  end
  
  def self.create_user_from_omniauth(auth)
    create(
      provider: auth['provider'],
      uid: auth['uid'],
      name: auth['info']['name'],
      about: auth['info']['description'],
      email: auth['info']['email']
      )
  end
  
  def getToken( idToCode ) 
    
    require "base64"
    token  = Base64.encode64("%d" % idToCode)
    return token
  end 
  
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :contributions]
  
  helper_method :getToken, :decodedToken

  # GET /users
  # GET /users.json
  def index
    @users = User.all
    #@contributions = Contributions.all
    
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user  = User.find(params[:id])
    if params[:submission_type] == "contributions"
     @contributions = Contribution.where(user_id: @user.id).order(created_at: :desc)
     render :json => @contributions
    elsif params[:submission_type] == "comments"
      @comments = Comment.where(user_id: @user.id).order(created_at: :desc)
      render :json => @comments
    elsif params[:submission_type] == "replies"
      @replies = Reply.where(user_id: @user.id).order(created_at: :desc)
      render :json => @replies
    elsif params[:submission_type] == nil
      #render :json => @user
      render :show
    else 

      render :json => {:status => "400", :error => "No es un tipo valido"}, status: :bad_request
    end
  end

  # GET /users/1/contributions
  def contributions
    @user = User.find(params[:id])
    @contributions = @user.contributions.paginate(page: params[:page])
  end
  

  # GET /login
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # POST /loginP
  # POST /loginP.json
  def login
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    id = decodeToken(params[:user_token])
    if (@user.id == id)
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
          format.json { render :show, status: :ok, location: @user }
        else
          format.html { render :edit }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
    else
       render :json => {:status => "401", :error => "No estas autorizado a editar el perfil"}, status: :unauthorized
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def contributions
    @user  = User.find(params[:id])
    @contributions = Contribution.where(user_id: @user.id).order(created_at: :desc)
    render 'showcontribution'
  end
  
  def comments
    @user  = User.find(params[:id])
    @comments = Comment.where(user_id: @user.id).order(created_at: :desc)
    render 'showcomments'
  end
  
  def replies
    @user  = User.find(params[:id])
    @replies = Reply.where(user_id: @user.id).order(created_at: :desc)
    render 'showreplies'
  end
  
  def edit
    @user  = User.find(params[:id])
    render 'edit'
    
  end
  
  def threads
    @user  = User.find(params[:id])
    @comments = Comment.where(user_id: @user.id).order(created_at: :desc)
    @replies = Reply.where(user_id: @user.id).order(created_at: :desc)
    render 'showthreads'
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :about, :karma)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_LoginCreateAccount.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_editform.html.erb
<%= render 'form' %> 

app/views/users/_form.html.erb
  <%= render 'static_pages/header' %>
  <%= render 'static_pages/menu' %>
<div class="page-content">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :about %><br>
    <%= f.text_area :about %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

</div>
<%= render 'static_pages/footer' %>

app/views/users/_loginform.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_newform.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'editform' %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Created</th>
      <th>Karma</th>
      <th>About</th>
      <th>Email</th>
      <th>Token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.password %></td>
        <td><%= user.created_at %></td>
        <td><%= user.karma %></td>
        <td><%= user.about %></td>
        <td><%= user.email %></td>
        <td><%= user.getToken(user.id) %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<h3>Login</h3>



<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h3>Login</h3>
<%= render 'loginform' %>

<h4>Passwords should be at least 8 characters. Please choose another. </h4>

<h3>Create Acount</h3>

<%= render 'newform' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
  <%= render 'static_pages/header' %>
  <%= render 'static_pages/menu' %>
  <div class="page-content">
      <div class="user-wrapper">
        <div class="flex-wrapper">
          <div class="title">User:</div>
          <div class="user-content"><%=@user.name %> </div>
        </div>
        <div class="flex-wrapper">
          <div class="title">Created:</div>
          <div class="user-content"><%= "#{time_ago_in_words(@user.created_at)} ago" %></div>
        </div>
        <!--
        <div class="flex-wrapper">
          <div class="title">Karma:</div>
          <div class="user-content"><%=@user.karma %></div>
        </div>-->
         <div class="flex-wrapper">
          <div class="title">Email:</div>
          <div class="user-content"><%=@user.email %></div>
        </div>
        <div class="flex-wrapper">
          <div class="title">About:</div>
          <div class="user-content"><%=@user.about %></div>
        </div>
        <br>
        <div style="font-weight: bold"> <%= link_to("Contributions", controller: "users", action:"contributions", :id => @user) %> </div>
        <div style="font-weight: bold"> <%= link_to("Comments", controller: "users", action:"comments", :id => @user) %> </div>
        <div style="font-weight: bold"> <%= link_to("Replies", controller: "users", action:"replies", :id => @user) %> </div>
        <br>
        <% if (current_user && current_user.name==@user.name)%>
        <div style="font-weight: bold"> <%= link_to("Edit", controller: "users", action:"edit", :id => @user) %>
        <% end %>
    </div>
  </div>
  
  
  
  <%= render 'static_pages/footer' %>

app/views/users/showcomments.html.erb
  <%= render 'static_pages/header' %>
  <%= render 'static_pages/menu' %>

<div class="page-content">

<p id="notice"><%= notice %></p>

  <div class="contributions">
    <% @comments.each.with_index(1) do |comment, index| %>
      <div class="item">
        <div>
          <span><%= index%>. &nbsp;</span>
        </div>
        <div>
          <span>
          <% if current_user %>
            <%= link_to image_tag("https://news.ycombinator.com/grayarrow.gif"), like_comment_path(comment), method: :put %>
          <% else %>
            <%= link_to image_tag("https://news.ycombinator.com/grayarrow.gif"), "/auth/twitter" %>
          <% end %>
          </span>
          &nbsp;
        </div>
        <div>
          <div>
            <%= comment.content %>
          </div>
          
          <div class="bottom">
            <span style="color:grey">
              <%= link_to "#{getAuthor(comment.user_id)}", "/users/#{comment.user_id}" %>
              <%= time_ago_in_words(comment.created_at) %> ago | on: 
              
              <%= link_to "#{comment.contribution.titulo}", "/contributions/#{comment.contribution.id}" %>
            </span>
            
          </div>
          
        </div>
        
          
      </div>
    <% end %>
  </div>
</div>
<%= render 'static_pages/footer' %>

app/views/users/showcontribution.html.erb
  <%= render 'static_pages/header' %>
  <%= render 'static_pages/menu' %>
  
  <div class="page-content">
    <div class="contributions">
    <% @contributions.each.with_index(1) do |contribution, index| %>

          <div class="item">
            
            <div>
              <span>
              <% if current_user %>
              <%= link_to like_contribution_path(contribution), method: :put do %>
                      <img src="https://news.ycombinator.com/grayarrow.gif"></img>
              <% end %>
              <% else %>
                <%= link_to image_tag("https://news.ycombinator.com/grayarrow.gif"), "/auth/twitter" %>
              <% end %>
              </span>
            </div>
            
            <div>
            &nbsp; <%= index %>. &nbsp;
            </div>
            <div>
            
              <span class="topic_title"><%= link_to "#{contribution.titulo}", contribution%></span>
              <% if contribution.url != ""  %>
                (<span class="topic_url"><a href="http://<%= contribution.url %>"><%= contribution.url %></a></span>)
              <% end %>
              
              <div class="bottom">
                <span style="color:grey"><%= contribution.votes_for.size %>
                <% if contribution.votes_for.size < 2  %>
                  point by
                <% else %>
                  points by
                <% end %>
                <%= link_to "#{getAuthor(contribution.user_id)}", "/users/#{contribution.user_id}" %>
                <%= time_ago_in_words(contribution.created_at) %> ago | 
                <% if contribution.comments.size == 0  %>
                  <%= link_to "0 comments", contribution %>
                <% else %>
                  <%= link_to "#{contribution.comments.size + contribution.replies.size} comments", contribution %>
                <% end %>
                </span>
                
              </div>
            </div>
      </div>
    <% end %>
    </div>
    
    </div>
    

  <%= render 'static_pages/footer' %>

app/views/users/showreplies.html.erb
  <%= render 'static_pages/header' %>
  <%= render 'static_pages/menu' %>
  
<div class="page-content">
  

  <p id="notice"><%= notice %></p>
  <div class="contributions">
    <% @replies.each.with_index(1) do |reply, index| %>
      <div class="item">
        <div>
          <span><%= index%>.</span>&nbsp;
        </div>
        <div>
          <span>
          <% if current_user %>
            <%= link_to image_tag("https://news.ycombinator.com/grayarrow.gif"), like_reply_path(reply), method: :put %>
          <% else %>
            <%= link_to image_tag("https://news.ycombinator.com/grayarrow.gif"), "/auth/twitter" %>
          <% end %>
          
          </span>
        </div>
        <div>
          <div>
            &nbsp;<%= reply.content %>
          </div>
          
          <div class="bottom">
            <span>
            <%= link_to "#{getAuthor(reply.user_id)}", "/users/#{reply.user_id}", {style: "color: grey"}%>
            <%= time_ago_in_words(reply.created_at) %> ago | 
            <%= link_to "parent", "/comments/#{reply.comment.id}", {style: "color: grey"}%>
            | on: 
            <%= link_to "#{reply.contribution.titulo}", "/contributions/#{reply.comment.contribution.id}", {style: "color: grey"}%>
          </span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

  <%= render 'static_pages/footer' %>

app/views/users/showthreads.html.erb
<%= render 'static_pages/header' %>
<%= render 'static_pages/menu' %>

<div class="page-content">

    <h3><%=current_user.name %>'s Comments</h3>
    <div class="contributions">
      <% @comments.each.with_index(1) do |comment, index| %>
      <div class="item">
        <div>
          <span><%= index%>.</span>&nbsp;
        </div>
        <div>
          <span>
            <% if current_user %>
              <%= link_to image_tag("https://news.ycombinator.com/grayarrow.gif"), like_comment_path(comment), method: :put %>
            <% else %>
              <%= link_to image_tag("https://news.ycombinator.com/grayarrow.gif"), "/auth/twitter" %>
            <% end %>
          </span>&nbsp;
        </div>
        <div>
          <div>
            <%= comment.content %>
          </div>
          <div class="bottom">
            <span style="color:grey">
              <%= link_to "#{getAuthor(comment.user_id)}", "/users/#{comment.user_id}", {style: "color: grey"}%>
              <%= time_ago_in_words(comment.created_at) %> ago | on: 
              
              <%= link_to "#{comment.contribution.titulo}", "/contributions/#{comment.contribution.id}", {style: "color: grey"}%>
            </span>
          </div>
        </div>
      </div>
      
      <% end %>
    </div>
    
    <h3><%= current_user.name %>'s Replies</h3>
    <div class="contributions">
       <% @replies.each.with_index(1) do |reply, index| %>
       
       <div class="item">
         <div>
           <span class="rank"><%= index%>.</span>&nbsp;
         </div>
         <div>
           <span class="reply_link">
          <% if current_user %>
            <%= link_to image_tag("https://news.ycombinator.com/grayarrow.gif"), like_reply_path(reply), method: :put %>
          <% else %>
            <%= link_to image_tag("https://news.ycombinator.com/grayarrow.gif"), "https://my-hacker-news-project.herokuapp.com/auth/twitter" %>
          <% end %>
          </span>&nbsp;
         </div>
         <div>
          <div>
            <%= reply.content %>
          </div>
          <div class="bottom">
            <%= link_to "#{getAuthor(reply.user_id)}", "/users/#{reply.user_id}" %>
            <%= time_ago_in_words(reply.created_at) %> ago | 
            <%= link_to "parent", "/comments/#{reply.comment.id}" %>
            | on: 
            <%= link_to "#{reply.contribution.titulo}", "/contributions/#{reply.comment.contribution.id}" %>
          </div>
         </div>
       </div>
        
    <% end %>
    </div>
   


</div>
<%= render 'static_pages/footer' %>