config/routes.rb
Rails.application.routes.draw do
  resources :replies
  resources :comments
  resources :contributions
  resources :users
  
  get 'comment/new'
  
  get 'static_pages/home'
  
  
  root 'static_pages#home'
  
  
  resources :static_pages do
    resources :contributions
  end
  
  resources :users do
    member do
      get :contributions, :comments, :replies, :threads
    end
  end
  
  resources :contributions do
      resources :comments
  end
  
  resources :comments do
      resources :replies
  end
  
  
  resources :contributions do
  member do
      put "like", to: "contributions#upvote"
    end
  end
  
  resources :comments do
  member do
      put "like", to: "comments#upvote"
    end
  end
  
  resources :replies do
  member do
      put "like", to: "replies#upvote"
    end
  end
  

  get 'home' => 'layouts#home'
  
  get 'login' => 'users#new'
  
  get 'contributions' => 'contributions#index'
  
  get 'asks' => 'asks#index'
  
  post '/replies' => 'replies#new'
  
  get '/auth/twitter/callback', to: 'sessions#create'
  
  delete '/sign_out', to: 'sessions#destroy'

end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :replies
    acts_as_votable
    #has_many :replies
    default_scope -> { order(created_at: :desc) }
    #validates :user_id, presence: true
    #validates :titulo, presence: true, length: { maximum: 140 }
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
    before_action :set_contribution, only: [:show, :edit, :update, :destroy]

  def upvote
  
    if(current_user)
      @contributions = Contribution.find(params[:id])
      @contributions.liked_by current_user
      @contributions.update(puntos: @contributions.votes_for.size)
      redirect_to root_path
    else 
      @contributions = Contribution.find(params[:id])
      myId = decodeToken(params[:user_token])
      @user =  User.find(myId)
      if(@user.voted_for? @contributions)
         render :json => {:status => "403", :error => "El usuario ya ha votado esta contribucion"}, status: :forbidden
      else 
        @contributions.liked_by @user
        @contributions.update(puntos: @contributions.votes_for.size)
        
          render :json => {status => "200", :id => params[:id], :text => @contributions.text, 
          :url => @contributions.url , :titulo => @contributions.titulo, :user_id => @contributions.user_id, 
          :created_at => @contributions.created_at, :puntos => @contributions.puntos }
          #format.json { render :show, status: :ok, location: @contributions }
      end
    end
    
  end
  
  #def upvote 
  #  @contributions = Contribution.find(params[:id])
  #  @contributions.upvote_by current_user
  #  redirect_to :back
  #end
  
  def downvote
    @contributions = Contribution.find(params[:id])
    @contributions.downvote_by current_user
    redirect_to :back
  end

  # GET /contributions
  # GET /contributions.json
  def index
    if params[:contribution_type] == "show"
      @contributions = Contribution.where.not(url: '').order(created_at: :desc)
    elsif params[:contribution_type] == "ask"
      @contributions  = Contribution.where.not(text: '').order(created_at: :desc)
    elsif params[:contribution_type] == nil || params[:contribution_type] == ''
      @contributions  = Contribution.all.order(created_at: :desc)
    else
     render :json => {:status => "400", :error => "Bad Request"}, status: :bad_request
    end
  end
  
  # GET /contributions/users/1
  # GET /contributions/users/1.json
  def threads
    @threads = Contribution.where("user_id=?",params[:id]).all.order("created_at desc")
  end

  # GET /contributions/1
  # GET /contributions/1.json
  def show
    @comment = Comment.new
  end

  # GET /contributions/new
  def new
    @contribution = Contribution.new
  end

  # GET /contributions/1/edit
  def edit
  end

  # POST /contributions
  # POST /contributions.json
  def create
      if (current_user)
        @contribution = Contribution.new(contribution_params)
        respond_to do |format|
          if @contribution.save
            format.html { redirect_to "" }
            format.json { render :index, status: :created, location: @contribution }
          else
            format.html { render :new }
            format.json { render json: @contribution.errors, status: :unprocessable_entity }
          end
        end
      elsif (params[:contribution][:url] != nil && params[:contribution][:text] != nil) || 
      (params[:contribution][:url] == nil && params[:contribution][:text] == nil) 
        render :json => {:status => "400", :error => "Bad Request"}, status: :bad_request
      else
        miId = decodeToken(params[:user_token])
        @miuser = User.find(miId) # comprueba que no existe el user con exte token
        params[:contribution][:user_id] = miId
        params[:contribution][:puntos] = 0;
        @contribution = Contribution.new(contribution_params)
        respond_to do |format|
          if @contribution.save
            format.html { redirect_to "" }
            format.json { render :show, status: :created, location: @contribution }
          else
            format.html { render :new }
            format.json { render json: @contribution.errors, status: :unprocessable_entity }
          end
        end
      end  
  end

  # PATCH/PUT /contributions/1
  # PATCH/PUT /contributions/1.json
  def update
    respond_to do |format|
      if @contribution.update(contribution_params)
        format.html { redirect_to @contribution, notice: 'Contribution was successfully updated.' }
        format.json { render :show, status: :ok, location: @contribution }
      else
        format.html { render :edit }
        format.json { render json: @contribution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contributions/1
  # DELETE /contributions/1.json
  def destroy
    @contribution.destroy
    respond_to do |format|
      format.html { redirect_to contributions_url, notice: 'Contribution was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contribution
      @contribution = Contribution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contribution_params
      params.require(:contribution).permit(:titulo, :url, :puntos, :text, :tipo, :user_id)
    end
    
end

app/helpers/contributions_helper.rb
module ContributionsHelper
end

app/views/contributions/_contribution.html.erb
<li id="contribution-<%= contribution.id %>">
  
  <span>
    <%= contribution.titulo %>
  </span>
  
  <span>
    (<%= contribution.url %>)
  </span>
  
  <span>
    <%= contribution.puntos %>
  </span>
  
  <br>
  
  <span>
    points by
  </span>

  <span>
     <%= link_to contribution.user.name, contribution.user %>
  </span>
  
  <span>
    <%= link_to time_ago_in_words(contribution.created_at), contribution %>
  </span>
  
  <span>
    <%= link_to "#{contribution.comments.size + contribution.replies.size} comments", contribution %>
  </span>
  <span>
    <%= link_to 'Destroy', contribution, method: :delete, data: { confirm: 'Are you sure?' } %>
  </span>
</li>
<br>

app/views/contributions/_form.html.erb
<%= form_for(@contribution) do |f| %>
  <% if @contribution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contribution.errors.count, "error") %> prohibited this contribution from being saved:</h2>

      <ul>
      <% @contribution.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="label">
    <%= f.label :titulo %>
    </div>
    <%= f.text_field :titulo %>
  </div>

  <div class="field">
     <%= f.hidden_field( :user_id, :value => current_user.id )%>
  </div>
  
  <div class="field">
    <div class="label">
    <%= f.label :url %>
    </div>
    <%= f.text_field :url %>
  </div>
  
  <div class="field">
    <div class="label">
    <%= f.label :text %>
    </div>
    <%= f.text_area :text %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/contributions/contributions.html.erb
      
    <div class="item">
      <div>
      <div>
          <span class="titulo"><%= link_to "#{contribution.titulo}", contribution%></span>
          <span class="url"><a href="http://<%= contribution.url %>">(<%= contribution.url %>)</a></span>
      </div>
      <div class="bottom">
          <span><%= contribution.puntos %> points,</span>
          <span>by <%= link_to "#{getAuthor(contribution.user_id)}", "/users/#{contribution.user_id}", {style: "color: grey"}%></span>
          <span><%= link_to "#{time_ago_in_words(contribution.created_at)} ago", contribution %> </span>
          <span><%= link_to "#{contribution.comments.size + contribution.replies.size} comments", contribution %></span>
      </div>
      </div>
    </div>
        


<div>
  <aside>
    <section>
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
  <div>
    <% if @user.contributions.any? %>
      <h3>Contributions (<%= @user.contributions.count %>)</h3>
      <ol>
        <%= render @contributions %>
      </ol>
      <%= will_paginate @contributions %>
    <% end %>
  </div>
</div>

app/views/contributions/edit.html.erb
<h1>Editing Contribution</h1>

<%= render 'form' %>

<%= link_to 'Show', @contribution %> |
<%= link_to 'Back', contributions_path %>

app/views/contributions/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home | Hacker News</title>
  </head>
    <%= render 'static_pages/header' %>
    <%= render 'static_pages/menu' %>
    
    <div class="page-content">
      <div class="contributions">
          <ol>
         <%= render @contributions %>
          </ol
        
      
      </div>
      
    </div>
    <%= render 'static_pages/footer' %>
  
</html>

app/views/contributions/new.html.erb
<%= render 'static_pages/header' %>
<%= render 'static_pages/menu' %>

<div class="page-content">
    
    <h2>Submit</h2>

    <%= render 'form' %>

    <p>Leave url blank to submit a question for discussion. If there is no url, the text (if any) will appear at the top of the thread.</p>

    <%= link_to 'Back', contributions_path %>

</div>

<%= render 'static_pages/footer' %>

app/views/contributions/show.html.erb
<%= render 'static_pages/header' %>
    <%= render 'static_pages/menu' %>
<div class="page-content">
  <div class="contributions">
    <div class="item">
      <div>
        <div>
          <span class="titulo">
            <%= @contribution.titulo %>
          </span>
          
          <span class="url">
            <% if @contribution.url != "" %>
            <a href="http://<%= @contribution.url %>">(<%= @contribution.url %>)</a>
            <% end %>
          </span>
        </div>
      
        <div class="bottom">
          <span>
            <%= @contribution.puntos %>
          </span>
          
          <span>
            points by
          </span>
        
          <span>
             <%= link_to @contribution.user.name, @contribution.user %>
          </span>
          
          <span>
            <%= link_to "#{time_ago_in_words(@contribution.created_at)} ago", @contribution %>
          </span>
        </div>
      </div>
    </div>
  </div>
  
  <div>
    <%= @contribution.text %>
  </div>
  
  <br>

  <% if (current_user) %>
    <%= render "comments/newComment" %>
  <% else %>
    <b>If you want to comment on this contribution, please <%= link_to 'sign in', '/auth/twitter' %></b>
  <% end %>
  <br>
  <br>
  
  <div class="comentarios">
      <% @contribution.comments.each do |comment| %>
          <div class="top">
            <%= link_to like_comment_path(comment), method: :put do %>
              <img src="https://news.ycombinator.com/grayarrow.gif"></img>
            <% end %>
            <span><%= link_to "#{getAuthor(comment.user_id)}", "/users/#{comment.user_id}" %></span> 
            <span><%= time_ago_in_words( comment.created_at ) %> ago</span>
            <span> <%= comment.get_upvotes.size %> points</span>
                
          </div>
          
          <div style="padding-left: 15px;"><%= comment.content %> </div>
          <% if (current_user) %>
            <%= link_to 'Reply', comment, {style: "margin-left: 15px"} %>
          <% else %>
            <%= link_to 'Reply', '/auth/twitter' %>
          <% end %>
          
          <div class="replies">
        <% comment.replies.each do |reply| %>
          <div class="reply">
            <div class="top">
              <%= link_to like_reply_path(reply), method: :put do %>
                <img src="https://news.ycombinator.com/grayarrow.gif"></img>
              <% end %>
              <span><%= link_to "#{getAuthor(reply.user_id)}", "/users/#{reply.user_id}" %></span>
              <span><%= time_ago_in_words( reply.created_at ) %> ago</span>
              <span> <%= reply.get_upvotes.size %> points</span>
            </div>
            <div class="reply-content" style="padding-left: 15px;">
              <%= reply.content %> 
            </div>
          </div>
        <%end%>
        </div>
      <% end %>
    </div>
</div>
<%= render 'static_pages/footer' %>

app/views/contributions/threads.html.erb
<% @contributions do |contribution| %>
    <div class="item">
      <div>
      <div>
          <span class="titulo"><%= link_to "#{contribution.titulo}", contribution%></span>
          <span class="url"><a href="http://<%= contribution.url %>">(<%= contribution.url %>)</a></span>
      </div>
      <div class="bottom">
          <span><%= contribution.puntos %> points,</span>
          <span>by <%= link_to "#{getAuthor(contribution.user_id)}", "/users/#{contribution.user_id}", {style: "color: grey"}%></span>
          <span><%= link_to "#{time_ago_in_words(contribution.created_at)} ago", contribution %> </span>
          <span><%= link_to "#{contribution.comments.size + contribution.replies.size} comments", contribution %></span>
      </div>
      </div>
    </div>
<% end %>